### ISSUE TITLE
Platform quarterpipe blocks don't align with wallrides/loops

### ISSUE THREAD

**Issue by SinasAppel** [BigBang1112/nations-converter#10]
I've converted the map ESL - Balalaika (Fullspeed map) from TMNF to TM2020. Sadly though, the loop and tube are broken because the platform quarterpipe block does not align with other walls/loops. Can they be realigned?
Here are some screenshots:
![Trackmania_hW0snaZzLP](https://user-images.githubusercontent.com/17566646/101960707-403bd500-3c08-11eb-83e9-9da108d9d847.jpg)
![Trackmania_NTxguoZpFf](https://user-images.githubusercontent.com/17566646/101960740-547fd200-3c08-11eb-8933-0076149e1886.jpg)

And the map for reference:
[ESL - Balalaika.Map.Gbx.zip](https://github.com/BigBang1112/nations-converter/files/5681864/ESL.-.Balalaika.Map.Gbx.zip)

This tool is absolutely amazing btw, thanks for developing!

**Comment by BigBang1112** [comment]
Thank you for the report. We are working on this issue with iNDEX and the plan is to release the fix of it tomorrow in 1.0.2 update.

**Comment by BigBang1112** [comment]
d8b817ed4ee7e50085cfaf88142cbf5fb5bdac9f Alignment has been done and will arrive in 1.0.2
