### ISSUE TITLE
Can´t play 256 maps in TM2020

### ISSUE THREAD

**Issue by Officer-Nasty** [BigBang1112/nations-converter#22]
The converter does it´s Job, but i can´t play bigger maps than the normal 64x64.
It says i need to set a starting point, but i can´t because i´m only allowed to be in the 48x48 in tm2020.
I can build 256 maps on my own with openplanet addon, but i can´t open a 256 map from the original game with a 256 sized editor in the new. :/

**Comment by Officer-Nasty** [comment]
Okay nice to hear. Nice converter btw, very sick tool thats what we needed :D 
Keep it up!

**Comment by smasher-101** [comment]
Excited for when we can :)

**Comment by smasher-101** [comment]
Any idea of when this functionality will be added?

**Comment by BigBang1112** [comment]
Sometime between September and October.

**Comment by smasher-101** [comment]
I have an idea for a workaround, I tried using a macroblock but those don't work unless you have all embedded items in the same folder structure as the map was saved with, and I can't seem to find all the items the program uses but I assume they are somewhere you can point me to?

**Comment by BigBang1112** [comment]
The way the grass ground is hardcoded makes this simply difficult. In the best case, it has to be rewritten, but currently this has not reached my coding priority list. xd

**Comment by BigBang1112** [comment]
Closing the issue due to upcoming rewrite plans.
