### ISSUE TITLE
Info about resaving maps & computing shadows

### ISSUE THREAD

**Issue by donadigo** [BigBang1112/nations-converter#7]
First of all, exceptional work!

After converting some maps, I noticed that maps that don't have computed shadows and that aren't re-saved in TMNF, convert but fail to open in TM2020 (Titlepack 48x48x48 doesn't exist). Now a message about this appears, but *after* the actual converstion was successfull which would imply that this has to be done in TM2020 instead. Am I correct about this? If computing shadows have to be done in TMNF, I would expect a message before actual conversion or something permament in the UI.

**Comment by BigBang1112** [comment]
There is no need to compute shadows or anything, TMNF does compute them in memory, TM2 map lightmaps are removed before the conversion. You should resave the map in TM2020 and calculate shadows there.
One thing I could point out from your message is that currently only default size Stadium map base is supported.

**Comment by BigBang1112** [comment]
As 48x4848x48 bug has been resolved a month ago and due to further inactivity, I'm closing the issue for now.
