### ISSUE TITLE
Mediatracker clip positions in "In-game" are incorrect for TM2 maps.

### ISSUE THREAD

**Issue by zai-tm** [BigBang1112/nations-converter#8]
This might be because of the centering, but I don't know.
[Map for refrence](https://cdn.discordapp.com/attachments/786883166178246676/787022559887097967/Very_fast_super_speed.Map.Gbx)

**Comment by BigBang1112** [comment]
This issue is related to a feature of "3x3 trigger coords per 1 block coord" that has been added a little after TM2 Stadium release. I figured out in which case this issue happens so it will be fixed in the next update.

**Comment by BigBang1112** [comment]
I'm closing this issue because this has been figured out.
